# Generated by Django 2.0.2 on 2018-02-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='category/image/default.png', upload_to='category/image/'),
        ),
    ]
