# Generated by Django 2.0.2 on 2018-02-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='category/static/category/default.png', upload_to='category/static/category'),
        ),
    ]
