# Generated by Django 2.0.2 on 2018-02-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_auto_20180205_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='static/category'),
        ),
    ]
