# Generated by Django 2.0.2 on 2018-02-09 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0014_usertestsscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertestsscore',
            name='score',
        ),
    ]
