# Generated by Django 2.0.2 on 2018-02-09 15:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0015_remove_usertestsscore_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertestsscore',
            name='score',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertestsscore',
            name='title',
            field=models.TextField(default=datetime.datetime(2018, 2, 9, 15, 40, 36, 30044, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
